services:

  postgres:
    image: postgres:16
    container_name: arrels_postgres
    environment:
      POSTGRES_USER: arrels
      POSTGRES_PASSWORD: password
      POSTGRES_DB: arrels_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    container_name: arrels_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/arrels_db

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: arrels_mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./hardware/mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
  postgres_data:
  mongodb_data: