"""
Script para poblar la tabla productos con datos de ejemplo.
Ejecutar desde la carpeta backend/:
    python seed_productos.py
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from database import SessionLocal
from models.producto import Producto

db = SessionLocal()

productos = [
  # ── FRUTAS ───────────────────────────────────────────────────
  {"nombre_es":"Naranja Navel","nombre_en":"Navel Orange","descripcion_es":"Naranja de mesa dulce y sin semillas.","descripcion_en":"Sweet seedless table orange.","precio":1.80,"unidad":"kg","categoria":"frutas","stock":200,"stock_minimo":20,"destacado":True,"origen":"Agost, Alicante","certificado":"Producción Integrada"},
  {"nombre_es":"Naranja Valencia Late","nombre_en":"Valencia Late Orange","descripcion_es":"Naranja tardía de zumo con alta vitamina C.","descripcion_en":"Late juice orange with high vitamin C.","precio":1.50,"unidad":"kg","categoria":"frutas","stock":180,"stock_minimo":20,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Naranja Sanguina","nombre_en":"Blood Orange","descripcion_es":"Naranja de pulpa rojiza, sabor afrutado y ligeramente ácido.","descripcion_en":"Red-fleshed orange, fruity and slightly acidic.","precio":2.20,"unidad":"kg","categoria":"frutas","stock":100,"stock_minimo":10,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Limón Verna","nombre_en":"Verna Lemon","descripcion_es":"Limón de piel gruesa y gran tamaño, ideal para cocina.","descripcion_en":"Thick-skinned large lemon, great for cooking.","precio":1.60,"unidad":"kg","categoria":"frutas","stock":150,"stock_minimo":15,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Limón Eureka","nombre_en":"Eureka Lemon","descripcion_es":"Limón de piel fina y mucho zumo.","descripcion_en":"Thin-skinned lemon with high juice content.","precio":1.70,"unidad":"kg","categoria":"frutas","stock":130,"stock_minimo":15,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Limón Fino","nombre_en":"Fino Lemon","descripcion_es":"Variedad más dulce y aromática, muy apreciada en gastronomía.","descripcion_en":"Sweeter and more aromatic variety, prized in gastronomy.","precio":1.90,"unidad":"kg","categoria":"frutas","stock":90,"stock_minimo":10,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Uva Monastrell","nombre_en":"Monastrell Grape","descripcion_es":"Uva tinta autóctona de Alicante, base de grandes vinos.","descripcion_en":"Native red grape from Alicante, base of great wines.","precio":2.50,"unidad":"kg","categoria":"frutas","stock":120,"stock_minimo":10,"destacado":True,"origen":"Agost, Alicante","certificado":"DO Alicante"},
  {"nombre_es":"Uva Moscatel Embolsada","nombre_en":"Muscat Grape Vinalopó","descripcion_es":"Uva de mesa muy aromática y dulce, típica del Vinalopó.","descripcion_en":"Very aromatic sweet table grape, typical of Vinalopó.","precio":3.00,"unidad":"kg","categoria":"frutas","stock":100,"stock_minimo":10,"destacado":True,"origen":"Vinalopó, Alicante","certificado":"IGP Uva Embolsada del Vinalopó"},
  {"nombre_es":"Uva Airén","nombre_en":"Airén Grape","descripcion_es":"Uva blanca de vinificación con buena acidez y frescura.","descripcion_en":"White wine grape with good acidity and freshness.","precio":1.80,"unidad":"kg","categoria":"frutas","stock":80,"stock_minimo":10,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Melocotón Amarillo","nombre_en":"Yellow Peach","descripcion_es":"Melocotón clásico de pulpa amarilla, jugoso y aromático.","descripcion_en":"Classic yellow-fleshed peach, juicy and aromatic.","precio":2.00,"unidad":"kg","categoria":"frutas","stock":100,"stock_minimo":10,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Melocotón Paraguayo","nombre_en":"Flat Peach","descripcion_es":"Melocotón chato con hueso pequeño, muy dulce y sin fibra.","descripcion_en":"Flat peach with small pit, very sweet and fibre-free.","precio":2.80,"unidad":"kg","categoria":"frutas","stock":80,"stock_minimo":10,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Nectarina Roja","nombre_en":"Red Nectarine","descripcion_es":"Fruta de piel lisa y pulpa firme con intenso sabor dulce.","descripcion_en":"Smooth-skinned fruit with firm flesh and intense sweet flavour.","precio":2.20,"unidad":"kg","categoria":"frutas","stock":90,"stock_minimo":10,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Ciruela Reina Claudia","nombre_en":"Greengage Plum","descripcion_es":"Ciruela verde de pulpa melosa, muy apreciada para mermeladas.","descripcion_en":"Green plum with honey-like flesh, prized for jams.","precio":2.30,"unidad":"kg","categoria":"frutas","stock":70,"stock_minimo":8,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Ciruela Japonesa","nombre_en":"Japanese Plum","descripcion_es":"Ciruela roja de piel brillante y sabor dulce-ácido.","descripcion_en":"Red plum with shiny skin and sweet-tart flavour.","precio":2.10,"unidad":"kg","categoria":"frutas","stock":80,"stock_minimo":8,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Ciruela Negra","nombre_en":"Black Plum","descripcion_es":"Ciruela de piel oscura y pulpa roja, muy sabrosa y jugosa.","descripcion_en":"Dark-skinned plum with red flesh, very tasty and juicy.","precio":2.40,"unidad":"kg","categoria":"frutas","stock":60,"stock_minimo":8,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Granada Mollar","nombre_en":"Mollar Pomegranate","descripcion_es":"Granada dulce con granos tiernos sin semilla dura.","descripcion_en":"Sweet pomegranate with tender seedless arils.","precio":3.50,"unidad":"kg","categoria":"frutas","stock":60,"stock_minimo":8,"destacado":True,"origen":"Elche, Alicante","certificado":"DO Granada Mollar de Elche"},
  {"nombre_es":"Granada Agridulce","nombre_en":"Sweet-Sour Pomegranate","descripcion_es":"Granada con punto ácido, ideal para zumos y ensaladas.","descripcion_en":"Tangy pomegranate, ideal for juices and salads.","precio":2.80,"unidad":"kg","categoria":"frutas","stock":50,"stock_minimo":8,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Granada Roja Intenso","nombre_en":"Deep Red Pomegranate","descripcion_es":"Variedad de color granate intenso, alta en antioxidantes.","descripcion_en":"Deep garnet variety, high in antioxidants.","precio":3.20,"unidad":"kg","categoria":"frutas","stock":40,"stock_minimo":5,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Higo Negro","nombre_en":"Black Fig","descripcion_es":"Higo de piel oscura y pulpa roja, muy dulce y carnoso.","descripcion_en":"Dark-skinned fig with red flesh, very sweet and fleshy.","precio":4.00,"unidad":"kg","categoria":"frutas","stock":40,"stock_minimo":5,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Higo Verde","nombre_en":"Green Fig","descripcion_es":"Higo de verano de piel verde y pulpa rosada.","descripcion_en":"Summer fig with green skin and pink flesh.","precio":3.80,"unidad":"kg","categoria":"frutas","stock":35,"stock_minimo":5,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Higo Chumbo","nombre_en":"Prickly Pear","descripcion_es":"Fruto del nopal, refrescante y rico en fibra. Típico del secano alicantino.","descripcion_en":"Cactus pear fruit, refreshing and fibre-rich.","precio":2.50,"unidad":"kg","categoria":"frutas","stock":50,"stock_minimo":5,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Mandarina Clementina","nombre_en":"Clementine","descripcion_es":"Mandarina sin semillas de fácil pelado y sabor dulce.","descripcion_en":"Seedless easy-peel mandarin with sweet flavour.","precio":1.70,"unidad":"kg","categoria":"frutas","stock":150,"stock_minimo":15,"destacado":True,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Mandarina Orri","nombre_en":"Orri Mandarin","descripcion_es":"Mandarina tardía de alto contenido en azúcar.","descripcion_en":"Late mandarin with high sugar content.","precio":2.00,"unidad":"kg","categoria":"frutas","stock":120,"stock_minimo":15,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Mandarina Hernandina","nombre_en":"Hernandina Mandarin","descripcion_es":"Variedad de media estación con equilibrio dulce-ácido.","descripcion_en":"Mid-season variety with sweet-acid balance.","precio":1.80,"unidad":"kg","categoria":"frutas","stock":100,"stock_minimo":10,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Sandía Crimson Sweet","nombre_en":"Crimson Sweet Watermelon","descripcion_es":"Sandía de pulpa roja intensa y alto contenido en azúcar.","descripcion_en":"Watermelon with deep red flesh and high sugar content.","precio":0.60,"unidad":"kg","categoria":"frutas","stock":200,"stock_minimo":20,"destacado":True,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Sandía Mini Sin Pepitas","nombre_en":"Mini Seedless Watermelon","descripcion_es":"Sandía pequeña sin pepitas, perfecta para familias reducidas.","descripcion_en":"Small seedless watermelon, perfect for small families.","precio":1.20,"unidad":"kg","categoria":"frutas","stock":100,"stock_minimo":10,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Melón Piel de Sapo","nombre_en":"Toad Skin Melon","descripcion_es":"Melón de piel verde rugosa y pulpa muy dulce y blanca.","descripcion_en":"Rough green-skinned melon with very sweet white flesh.","precio":0.80,"unidad":"kg","categoria":"frutas","stock":150,"stock_minimo":15,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Cereza Picota","nombre_en":"Picota Cherry","descripcion_es":"Cereza española sin rabillo, dulce y crujiente.","descripcion_en":"Spanish stemless cherry, sweet and crunchy.","precio":5.00,"unidad":"kg","categoria":"frutas","stock":50,"stock_minimo":8,"destacado":False,"origen":"Alicante","certificado":None},
  {"nombre_es":"Cereza Burlat","nombre_en":"Burlat Cherry","descripcion_es":"Primera cereza de la temporada, grande y de color rojo brillante.","descripcion_en":"First cherry of the season, large with bright red colour.","precio":4.50,"unidad":"kg","categoria":"frutas","stock":40,"stock_minimo":5,"destacado":False,"origen":"Alicante","certificado":None},
  {"nombre_es":"Cereza Negra","nombre_en":"Black Cherry","descripcion_es":"Cereza de maduración tardía, muy dulce y oscura.","descripcion_en":"Late-ripening cherry, very sweet and dark.","precio":5.50,"unidad":"kg","categoria":"frutas","stock":30,"stock_minimo":5,"destacado":False,"origen":"Alicante","certificado":None},
  {"nombre_es":"Aguacate Hass","nombre_en":"Hass Avocado","descripcion_es":"Aguacate de piel rugosa y pulpa cremosa, el más consumido.","descripcion_en":"Rough-skinned avocado with creamy flesh, the world's most consumed.","precio":3.50,"unidad":"kg","categoria":"frutas","stock":80,"stock_minimo":10,"destacado":False,"origen":"Alicante","certificado":None},
  {"nombre_es":"Aguacate Fuerte","nombre_en":"Fuerte Avocado","descripcion_es":"Aguacate de piel lisa y forma periforme, sabor suave y mantecoso.","descripcion_en":"Smooth pear-shaped avocado, mild and buttery.","precio":3.20,"unidad":"kg","categoria":"frutas","stock":60,"stock_minimo":8,"destacado":False,"origen":"Alicante","certificado":None},
  {"nombre_es":"Aguacate Reed","nombre_en":"Reed Avocado","descripcion_es":"Aguacate grande y redondo con pulpa de sabor intenso.","descripcion_en":"Large round avocado with intensely flavoured flesh.","precio":3.80,"unidad":"kg","categoria":"frutas","stock":40,"stock_minimo":5,"destacado":False,"origen":"Alicante","certificado":None},
  {"nombre_es":"Pera Conferencia","nombre_en":"Conference Pear","descripcion_es":"Pera alargada de pulpa jugosa y sabor suave.","descripcion_en":"Elongated pear with juicy flesh and mild flavour.","precio":1.90,"unidad":"kg","categoria":"frutas","stock":100,"stock_minimo":10,"destacado":False,"origen":"Alicante","certificado":None},
  {"nombre_es":"Pera Blanquilla","nombre_en":"Blanquilla Pear","descripcion_es":"Pera blanca de piel fina y sabor muy dulce.","descripcion_en":"White thin-skinned pear with very sweet flavour.","precio":1.70,"unidad":"kg","categoria":"frutas","stock":90,"stock_minimo":10,"destacado":False,"origen":"Alicante","certificado":None},
  {"nombre_es":"Manzana Fuji","nombre_en":"Fuji Apple","descripcion_es":"Manzana muy dulce y crujiente, de larga conservación.","descripcion_en":"Very sweet and crunchy apple with long shelf life.","precio":1.80,"unidad":"kg","categoria":"frutas","stock":120,"stock_minimo":15,"destacado":False,"origen":"Alicante","certificado":None},
  {"nombre_es":"Manzana Golden","nombre_en":"Golden Apple","descripcion_es":"Manzana amarilla de pulpa suave y sabor equilibrado.","descripcion_en":"Yellow apple with soft flesh and balanced flavour.","precio":1.60,"unidad":"kg","categoria":"frutas","stock":110,"stock_minimo":15,"destacado":False,"origen":"Alicante","certificado":None},
  {"nombre_es":"Manzana Granny Smith","nombre_en":"Granny Smith Apple","descripcion_es":"Manzana verde ácida, perfecta para repostería y zumos.","descripcion_en":"Tart green apple, perfect for baking and juices.","precio":1.70,"unidad":"kg","categoria":"frutas","stock":90,"stock_minimo":10,"destacado":False,"origen":"Alicante","certificado":None},
  {"nombre_es":"Kaki Rojo Brillante","nombre_en":"Rojo Brillante Persimmon","descripcion_es":"Caqui sin astringencia, dulce y jugoso, cosecha otoñal.","descripcion_en":"Astringency-free persimmon, sweet and juicy, autumn harvest.","precio":2.50,"unidad":"kg","categoria":"frutas","stock":70,"stock_minimo":8,"destacado":True,"origen":"Valencia","certificado":"DO Kaki Ribera del Xúquer"},
  {"nombre_es":"Kaki Chocolate","nombre_en":"Chocolate Persimmon","descripcion_es":"Caqui de pulpa marrón y sabor dulce a vainilla, sin astringencia.","descripcion_en":"Brown-fleshed persimmon with vanilla-sweet flavour.","precio":3.00,"unidad":"kg","categoria":"frutas","stock":40,"stock_minimo":5,"destacado":False,"origen":"Valencia","certificado":None},
  {"nombre_es":"Níspero","nombre_en":"Loquat","descripcion_es":"Fruta de primavera muy apreciada en la comarca de Callosa d'En Sarrià.","descripcion_en":"Spring fruit highly prized in the Callosa d'En Sarrià area.","precio":4.00,"unidad":"kg","categoria":"frutas","stock":30,"stock_minimo":5,"destacado":True,"origen":"Callosa d'En Sarrià, Alicante","certificado":"IGP Níspero de Callosa d'En Sarrià"},
  {"nombre_es":"Caqui Triumph","nombre_en":"Triumph Persimmon","descripcion_es":"Caqui astringente que se consume seco o muy maduro.","descripcion_en":"Astringent persimmon consumed dried or very ripe.","precio":2.20,"unidad":"kg","categoria":"frutas","stock":50,"stock_minimo":5,"destacado":False,"origen":"Valencia","certificado":None},
  {"nombre_es":"Chirimoya","nombre_en":"Cherimoya","descripcion_es":"Fruta tropical de pulpa blanca cremosa y sabor dulce.","descripcion_en":"Tropical fruit with creamy white flesh and sweet flavour.","precio":5.00,"unidad":"kg","categoria":"frutas","stock":25,"stock_minimo":3,"destacado":True,"origen":"Málaga/Alicante","certificado":None},

  # ── FRUTOS SECOS ─────────────────────────────────────────────
  {"nombre_es":"Almendra Marcona","nombre_en":"Marcona Almond","descripcion_es":"La reina de las almendras españolas, redonda y de sabor suave.","descripcion_en":"The queen of Spanish almonds, round with mild flavour.","precio":12.00,"unidad":"kg","categoria":"frutos_secos","stock":100,"stock_minimo":10,"destacado":True,"origen":"Agost, Alicante","certificado":"IGP Almendra de Alicante"},
  {"nombre_es":"Almendra Largueta","nombre_en":"Largueta Almond","descripcion_es":"Almendra larga y plana, muy aromática. Ideal para turrones.","descripcion_en":"Long flat almond, very aromatic. Ideal for nougat.","precio":10.00,"unidad":"kg","categoria":"frutos_secos","stock":80,"stock_minimo":10,"destacado":True,"origen":"Agost, Alicante","certificado":"IGP Almendra de Alicante"},
  {"nombre_es":"Almendra Comune","nombre_en":"Comune Almond","descripcion_es":"Almendra de uso industrial y repostería.","descripcion_en":"Almond for industrial and baking use.","precio":8.00,"unidad":"kg","categoria":"frutos_secos","stock":120,"stock_minimo":15,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Almendra Tostada Sin Sal","nombre_en":"Unsalted Roasted Almond","descripcion_es":"Almendra marcona tostada al horno sin sal añadida.","descripcion_en":"Oven-roasted marcona almond without added salt.","precio":14.00,"unidad":"kg","categoria":"frutos_secos","stock":60,"stock_minimo":8,"destacado":True,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Almendra Frita con Sal","nombre_en":"Salted Fried Almond","descripcion_es":"Almendra frita en aceite de oliva con sal marina, aperitivo clásico.","descripcion_en":"Almond fried in olive oil with sea salt, classic snack.","precio":13.00,"unidad":"kg","categoria":"frutos_secos","stock":70,"stock_minimo":10,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Nuez Castellana","nombre_en":"Castilian Walnut","descripcion_es":"Nuez de cáscara fina y sabor suave, alta en omega-3.","descripcion_en":"Thin-shelled walnut with mild flavour, high in omega-3.","precio":9.00,"unidad":"kg","categoria":"frutos_secos","stock":60,"stock_minimo":8,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Nuez Chandler","nombre_en":"Chandler Walnut","descripcion_es":"Variedad americana de gran tamaño y piel clara.","descripcion_en":"Large American variety with light-coloured skin.","precio":10.00,"unidad":"kg","categoria":"frutos_secos","stock":50,"stock_minimo":8,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Avellana Negreta","nombre_en":"Negreta Hazelnut","descripcion_es":"Variedad española de alta producción y sabor intenso.","descripcion_en":"Spanish high-yield variety with intense flavour.","precio":7.50,"unidad":"kg","categoria":"frutos_secos","stock":70,"stock_minimo":8,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Piñón Mediterráneo","nombre_en":"Mediterranean Pine Nut","descripcion_es":"Piñón del pino piñonero, ingrediente clave en la gastronomía mediterránea.","descripcion_en":"Stone pine nut, key ingredient in Mediterranean cuisine.","precio":35.00,"unidad":"kg","categoria":"frutos_secos","stock":20,"stock_minimo":3,"destacado":True,"origen":"España","certificado":None},
  {"nombre_es":"Pistache Natural","nombre_en":"Natural Pistachio","descripcion_es":"Pistacho con cáscara abierta, sin sal, sabor auténtico.","descripcion_en":"Open-shell pistachio, unsalted, authentic flavour.","precio":14.00,"unidad":"kg","categoria":"frutos_secos","stock":50,"stock_minimo":8,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Pistache Tostado y Salado","nombre_en":"Roasted Salted Pistachio","descripcion_es":"Pistacho tostado con sal marina, aperitivo clásico.","descripcion_en":"Roasted pistachio with sea salt, classic snack.","precio":15.00,"unidad":"kg","categoria":"frutos_secos","stock":60,"stock_minimo":8,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Dátil Medjool","nombre_en":"Medjool Date","descripcion_es":"El rey de los dátiles, carnoso y muy dulce.","descripcion_en":"The king of dates, fleshy and very sweet.","precio":12.00,"unidad":"kg","categoria":"frutos_secos","stock":40,"stock_minimo":5,"destacado":True,"origen":"España","certificado":None},
  {"nombre_es":"Uva Pasa Moscatel","nombre_en":"Muscat Raisin","descripcion_es":"Pasa de uva moscatel de Alicante, dulce y con pepitas.","descripcion_en":"Alicante muscat grape raisin, sweet with seeds.","precio":5.00,"unidad":"kg","categoria":"frutos_secos","stock":60,"stock_minimo":8,"destacado":True,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Higo Seco Natural","nombre_en":"Natural Dried Fig","descripcion_es":"Higo desecado al sol, sin azúcar añadido.","descripcion_en":"Sun-dried fig, no added sugar.","precio":6.00,"unidad":"kg","categoria":"frutos_secos","stock":50,"stock_minimo":8,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Higo Seco Relleno de Almendra","nombre_en":"Almond-Stuffed Dried Fig","descripcion_es":"Higo seco con almendra marcona en su interior, producto artesanal.","descripcion_en":"Dried fig stuffed with marcona almond, artisan product.","precio":9.00,"unidad":"kg","categoria":"frutos_secos","stock":30,"stock_minimo":5,"destacado":True,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Cacahuete Tostado Sin Sal","nombre_en":"Roasted Unsalted Peanut","descripcion_es":"Cacahuete tostado al horno sin sal, crujiente y sabroso.","descripcion_en":"Oven-roasted peanut without salt, crunchy and tasty.","precio":4.00,"unidad":"kg","categoria":"frutos_secos","stock":90,"stock_minimo":15,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Mix Frutos Secos Energía","nombre_en":"Energy Nut Mix","descripcion_es":"Mezcla de almendra, nuez, avellana y uva pasa para deportistas.","descripcion_en":"Almond, walnut, hazelnut and raisin mix for athletes.","precio":11.00,"unidad":"kg","categoria":"frutos_secos","stock":40,"stock_minimo":5,"destacado":True,"origen":"Agost, Alicante","certificado":None},

  # ── ACEITES ───────────────────────────────────────────────────
  {"nombre_es":"AOVE Arbequina 500ml","nombre_en":"EVOO Arbequina 500ml","descripcion_es":"Aceite virgen extra de oliva arbequina, sabor suave y afrutado. Cosecha propia.","descripcion_en":"Extra virgin olive oil from arbequina, mild and fruity. Own harvest.","precio":8.50,"unidad":"ud","categoria":"aceites","stock":80,"stock_minimo":10,"destacado":True,"origen":"Agost, Alicante","certificado":"DO Aceite Comunitat Valenciana"},
  {"nombre_es":"AOVE Arbequina 250ml","nombre_en":"EVOO Arbequina 250ml","descripcion_es":"AOVE de oliva arbequina en formato pequeño, ideal para regalo.","descripcion_en":"Arbequina EVOO in small format, ideal as a gift.","precio":5.00,"unidad":"ud","categoria":"aceites","stock":60,"stock_minimo":8,"destacado":False,"origen":"Agost, Alicante","certificado":"DO Aceite Comunitat Valenciana"},
  {"nombre_es":"AOVE Picual 500ml","nombre_en":"EVOO Picual 500ml","descripcion_es":"AOVE picual de sabor intenso y frutado verde.","descripcion_en":"Picual EVOO with intense green fruity flavour.","precio":8.00,"unidad":"ud","categoria":"aceites","stock":70,"stock_minimo":10,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"AOVE Hojiblanca 500ml","nombre_en":"EVOO Hojiblanca 500ml","descripcion_es":"AOVE hojiblanca equilibrado, notas de almendra verde y hierbas.","descripcion_en":"Balanced hojiblanca EVOO with green almond and herb notes.","precio":8.50,"unidad":"ud","categoria":"aceites","stock":50,"stock_minimo":8,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"AOVE Ecológico 500ml","nombre_en":"Organic EVOO 500ml","descripcion_es":"AOVE de cultivo ecológico certificado, sin pesticidas.","descripcion_en":"Certified organic EVOO, pesticide-free.","precio":11.00,"unidad":"ud","categoria":"aceites","stock":40,"stock_minimo":5,"destacado":True,"origen":"Agost, Alicante","certificado":"Ecológico CAAE"},
  {"nombre_es":"Aceite de Oliva Virgen 1L","nombre_en":"Virgin Olive Oil 1L","descripcion_es":"Aceite de oliva virgen para uso diario en cocina y aliños.","descripcion_en":"Virgin olive oil for daily cooking and dressings.","precio":7.00,"unidad":"ud","categoria":"aceites","stock":100,"stock_minimo":15,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"AOVE Aromatizado Romero 250ml","nombre_en":"Rosemary EVOO 250ml","descripcion_es":"AOVE infusionado con romero fresco del campo.","descripcion_en":"EVOO infused with fresh field rosemary.","precio":7.50,"unidad":"ud","categoria":"aceites","stock":30,"stock_minimo":5,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"AOVE Aromatizado Ajo 250ml","nombre_en":"Garlic EVOO 250ml","descripcion_es":"AOVE con ajo fresco, perfecto para sofritos y aliños.","descripcion_en":"EVOO with fresh garlic, perfect for sofrito and dressings.","precio":7.50,"unidad":"ud","categoria":"aceites","stock":30,"stock_minimo":5,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"AOVE Trufa Negra 100ml","nombre_en":"Black Truffle EVOO 100ml","descripcion_es":"AOVE con aroma de trufa negra, toque gourmet para cualquier plato.","descripcion_en":"EVOO with black truffle aroma, gourmet touch for any dish.","precio":12.00,"unidad":"ud","categoria":"aceites","stock":20,"stock_minimo":3,"destacado":True,"origen":"España","certificado":None},
  {"nombre_es":"Pack Degustación Aceites 3x100ml","nombre_en":"Olive Oil Tasting Pack 3x100ml","descripcion_es":"Pack con Arbequina, Picual y Hojiblanca. Ideal para regalo.","descripcion_en":"Pack with Arbequina, Picual and Hojiblanca. Ideal as a gift.","precio":15.00,"unidad":"ud","categoria":"aceites","stock":25,"stock_minimo":5,"destacado":True,"origen":"Agost, Alicante","certificado":None},

  # ── VINOS ─────────────────────────────────────────────────────
  {"nombre_es":"Vino Tinto Monastrell Joven","nombre_en":"Young Monastrell Red Wine","descripcion_es":"Vino tinto joven de monastrell con notas de frutos rojos.","descripcion_en":"Young monastrell red wine with red fruit notes.","precio":6.50,"unidad":"ud","categoria":"vinos","stock":80,"stock_minimo":10,"destacado":True,"origen":"Agost, Alicante","certificado":"DO Alicante"},
  {"nombre_es":"Vino Tinto Monastrell Crianza","nombre_en":"Monastrell Crianza Red Wine","descripcion_es":"Crianza 12 meses en barrica de roble, taninos sedosos.","descripcion_en":"12-month oak barrel ageing, silky tannins.","precio":10.00,"unidad":"ud","categoria":"vinos","stock":50,"stock_minimo":8,"destacado":True,"origen":"Agost, Alicante","certificado":"DO Alicante"},
  {"nombre_es":"Vino Tinto Reserva","nombre_en":"Red Wine Reserva","descripcion_es":"Reserva 24 meses, blend de monastrell y cabernet sauvignon.","descripcion_en":"24-month reserva, blend of monastrell and cabernet sauvignon.","precio":15.00,"unidad":"ud","categoria":"vinos","stock":30,"stock_minimo":5,"destacado":True,"origen":"Agost, Alicante","certificado":"DO Alicante"},
  {"nombre_es":"Vino Blanco Moscatel Seco","nombre_en":"Dry Muscat White Wine","descripcion_es":"Blanco seco de moscatel, floral y refrescante.","descripcion_en":"Dry muscat white, floral and refreshing.","precio":7.00,"unidad":"ud","categoria":"vinos","stock":60,"stock_minimo":8,"destacado":False,"origen":"Agost, Alicante","certificado":"DO Alicante"},
  {"nombre_es":"Vino Blanco Airén","nombre_en":"Airén White Wine","descripcion_es":"Blanco ligero y afrutado, ideal como aperitivo.","descripcion_en":"Light and fruity white, ideal as an aperitif.","precio":5.50,"unidad":"ud","categoria":"vinos","stock":70,"stock_minimo":10,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Vino Rosado Monastrell","nombre_en":"Monastrell Rosé Wine","descripcion_es":"Rosado de monastrell, color salmón intenso y sabor frutal.","descripcion_en":"Monastrell rosé, deep salmon colour and fresh fruity flavour.","precio":7.50,"unidad":"ud","categoria":"vinos","stock":50,"stock_minimo":8,"destacado":False,"origen":"Agost, Alicante","certificado":"DO Alicante"},
  {"nombre_es":"Vino Dulce Moscatel","nombre_en":"Sweet Muscat Wine","descripcion_es":"Moscatel dulce natural de Alicante, aromático y goloso.","descripcion_en":"Natural sweet muscat from Alicante, aromatic and luscious.","precio":9.00,"unidad":"ud","categoria":"vinos","stock":40,"stock_minimo":5,"destacado":True,"origen":"Agost, Alicante","certificado":"DO Alicante"},
  {"nombre_es":"Cava Brut Nature","nombre_en":"Brut Nature Cava","descripcion_es":"Espumoso por método tradicional, sin azúcar añadido.","descripcion_en":"Sparkling wine by traditional method, no added sugar.","precio":11.00,"unidad":"ud","categoria":"vinos","stock":30,"stock_minimo":5,"destacado":False,"origen":"España","certificado":"DO Cava"},
  {"nombre_es":"Vermut Artesanal Rojo","nombre_en":"Artisan Red Vermouth","descripcion_es":"Vermut rojo con hierbas mediterráneas locales.","descripcion_en":"Red vermouth made with local Mediterranean herbs.","precio":12.00,"unidad":"ud","categoria":"vinos","stock":25,"stock_minimo":3,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Pack Vinos Alicante 3 botellas","nombre_en":"Alicante Wine Pack 3 bottles","descripcion_es":"Selección de tinto, blanco y rosado de la cooperativa.","descripcion_en":"Selection of red, white and rosé from the cooperative.","precio":20.00,"unidad":"ud","categoria":"vinos","stock":20,"stock_minimo":3,"destacado":True,"origen":"Agost, Alicante","certificado":"DO Alicante"},

  # ── MIEL ──────────────────────────────────────────────────────
  {"nombre_es":"Miel de Azahar 500g","nombre_en":"Orange Blossom Honey 500g","descripcion_es":"Miel monofloral de flor de naranjo, suave y muy aromática.","descripcion_en":"Orange blossom monofloral honey, mild and very aromatic.","precio":7.00,"unidad":"ud","categoria":"miel","stock":60,"stock_minimo":8,"destacado":True,"origen":"Alicante","certificado":None},
  {"nombre_es":"Miel de Romero 500g","nombre_en":"Rosemary Honey 500g","descripcion_es":"Miel de romero con propiedades digestivas.","descripcion_en":"Rosemary honey with digestive properties.","precio":8.00,"unidad":"ud","categoria":"miel","stock":50,"stock_minimo":8,"destacado":False,"origen":"Alicante","certificado":None},
  {"nombre_es":"Miel de Tomillo 500g","nombre_en":"Thyme Honey 500g","descripcion_es":"Miel de tomillo silvestre, antiséptica y con sabor intenso.","descripcion_en":"Wild thyme honey, antiseptic with intense flavour.","precio":8.50,"unidad":"ud","categoria":"miel","stock":45,"stock_minimo":5,"destacado":False,"origen":"Alicante","certificado":None},
  {"nombre_es":"Miel de Mil Flores 500g","nombre_en":"Wildflower Honey 500g","descripcion_es":"Miel polifloral del campo alicantino, equilibrada y versátil.","descripcion_en":"Alicante polyfloral honey, balanced and versatile.","precio":6.50,"unidad":"ud","categoria":"miel","stock":80,"stock_minimo":10,"destacado":False,"origen":"Alicante","certificado":None},
  {"nombre_es":"Miel de Espliego 500g","nombre_en":"Lavender Honey 500g","descripcion_es":"Miel de lavanda con aroma floral intenso y color ámbar claro.","descripcion_en":"Lavender honey with intense floral aroma and light amber colour.","precio":9.00,"unidad":"ud","categoria":"miel","stock":35,"stock_minimo":5,"destacado":True,"origen":"Alicante","certificado":None},
  {"nombre_es":"Miel Ecológica 500g","nombre_en":"Organic Honey 500g","descripcion_es":"Miel de producción ecológica certificada.","descripcion_en":"Certified organic honey production.","precio":10.00,"unidad":"ud","categoria":"miel","stock":30,"stock_minimo":5,"destacado":True,"origen":"Alicante","certificado":"Ecológico"},
  {"nombre_es":"Miel de Almendro 500g","nombre_en":"Almond Blossom Honey 500g","descripcion_es":"Miel escasa de flor de almendro, una de las primeras del año.","descripcion_en":"Rare almond blossom honey, one of the first of the year.","precio":11.00,"unidad":"ud","categoria":"miel","stock":20,"stock_minimo":3,"destacado":True,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Miel con Almendras 250g","nombre_en":"Honey with Almonds 250g","descripcion_es":"Miel artesanal con almendra marcona troceada.","descripcion_en":"Artisan honey with chopped marcona almond.","precio":8.00,"unidad":"ud","categoria":"miel","stock":30,"stock_minimo":5,"destacado":True,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Propóleo en Miel 250g","nombre_en":"Propolis in Honey 250g","descripcion_es":"Miel enriquecida con propóleo, excelente para las defensas.","descripcion_en":"Honey enriched with propolis, excellent for the immune system.","precio":9.00,"unidad":"ud","categoria":"miel","stock":20,"stock_minimo":3,"destacado":False,"origen":"Alicante","certificado":None},
  {"nombre_es":"Polen de Abeja 250g","nombre_en":"Bee Pollen 250g","descripcion_es":"Polen fresco liofilizado, superalimento rico en proteínas.","descripcion_en":"Fresh freeze-dried pollen, superfood rich in protein.","precio":12.00,"unidad":"ud","categoria":"miel","stock":15,"stock_minimo":3,"destacado":False,"origen":"Alicante","certificado":None},
  {"nombre_es":"Miel Cruda Sin Filtrar 500g","nombre_en":"Raw Unfiltered Honey 500g","descripcion_es":"Miel en estado natural con propóleo, cera y polen.","descripcion_en":"Honey in natural state with propolis, wax and pollen.","precio":9.50,"unidad":"ud","categoria":"miel","stock":25,"stock_minimo":3,"destacado":False,"origen":"Alicante","certificado":None},
  {"nombre_es":"Miel con Nueces 250g","nombre_en":"Honey with Walnuts 250g","descripcion_es":"Miel cremosa con trozos de nuez, ideal para tostadas.","descripcion_en":"Creamy honey with walnut pieces, ideal for toast.","precio":7.50,"unidad":"ud","categoria":"miel","stock":35,"stock_minimo":5,"destacado":False,"origen":"Alicante","certificado":None},
  {"nombre_es":"Miel con Canela 250g","nombre_en":"Honey with Cinnamon 250g","descripcion_es":"Mezcla de miel de mil flores con canela de Ceilán molida.","descripcion_en":"Wildflower honey mixed with ground Ceylon cinnamon.","precio":6.00,"unidad":"ud","categoria":"miel","stock":40,"stock_minimo":5,"destacado":False,"origen":"Alicante","certificado":None},
  {"nombre_es":"Pack Miel Gourmet 3x250g","nombre_en":"Gourmet Honey Pack 3x250g","descripcion_es":"Pack con azahar, romero y espliego. Ideal para regalo.","descripcion_en":"Pack with orange blossom, rosemary and lavender. Ideal as a gift.","precio":20.00,"unidad":"ud","categoria":"miel","stock":20,"stock_minimo":3,"destacado":True,"origen":"Alicante","certificado":None},
  {"nombre_es":"Miel de Algarrobo 500g","nombre_en":"Carob Honey 500g","descripcion_es":"Miel oscura y espesa de algarrobo, sabor intenso y mineral.","descripcion_en":"Dark thick carob honey, intense and mineral flavour.","precio":8.00,"unidad":"ud","categoria":"miel","stock":30,"stock_minimo":5,"destacado":False,"origen":"Alicante","certificado":None},
  {"nombre_es":"Miel de Lavanda Ecológica 500g","nombre_en":"Organic Lavender Honey 500g","descripcion_es":"Miel de lavanda de producción ecológica, suave y muy aromática.","descripcion_en":"Organic lavender honey, mild and very aromatic.","precio":11.00,"unidad":"ud","categoria":"miel","stock":15,"stock_minimo":3,"destacado":False,"origen":"Alicante","certificado":"Ecológico"},

  # ── CONSERVAS ─────────────────────────────────────────────────
  {"nombre_es":"Mermelada de Naranja 350g","nombre_en":"Orange Marmalade 350g","descripcion_es":"Mermelada artesanal de naranja amarga con fruta propia.","descripcion_en":"Artisan bitter orange marmalade with our own fruit.","precio":4.50,"unidad":"ud","categoria":"conservas","stock":60,"stock_minimo":8,"destacado":True,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Mermelada de Higo con Nuez 350g","nombre_en":"Fig and Walnut Jam 350g","descripcion_es":"Mermelada de higo negro con nuez, elaboración tradicional.","descripcion_en":"Black fig jam with walnut, traditional preparation.","precio":5.00,"unidad":"ud","categoria":"conservas","stock":40,"stock_minimo":5,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Crema de Almendra Marcona 350g","nombre_en":"Marcona Almond Cream 350g","descripcion_es":"Crema de almendra marcona sin azúcar añadido.","descripcion_en":"Marcona almond cream, no added sugar.","precio":6.00,"unidad":"ud","categoria":"conservas","stock":35,"stock_minimo":5,"destacado":True,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Tomate Frito Artesanal 400g","nombre_en":"Artisan Tomato Sauce 400g","descripcion_es":"Sofrito de tomate casero con aceite de oliva virgen extra.","descripcion_en":"Home-style tomato sauce with extra virgin olive oil.","precio":3.50,"unidad":"ud","categoria":"conservas","stock":80,"stock_minimo":10,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Aceitunas Negras Aliñadas 350g","nombre_en":"Seasoned Black Olives 350g","descripcion_es":"Aceitunas negras con especias mediterráneas y AOVE.","descripcion_en":"Black olives with Mediterranean spices and EVOO.","precio":3.80,"unidad":"ud","categoria":"conservas","stock":60,"stock_minimo":8,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Aceitunas Verdes Rellenas de Anchoa 350g","nombre_en":"Anchovy-Stuffed Green Olives 350g","descripcion_es":"Aceitunas manzanilla rellenas de anchoa del Cantábrico.","descripcion_en":"Manzanilla olives stuffed with Cantabrian anchovy.","precio":4.20,"unidad":"ud","categoria":"conservas","stock":50,"stock_minimo":8,"destacado":True,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Paté de Aceitunas Negras 150g","nombre_en":"Black Olive Pâté 150g","descripcion_es":"Tapenada elaborada con aceitunas negras y alcaparras.","descripcion_en":"Tapenade made with black olives and capers.","precio":3.50,"unidad":"ud","categoria":"conservas","stock":40,"stock_minimo":5,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"All i Oli Artesanal 200g","nombre_en":"Artisan Alioli 200g","descripcion_es":"All i oli tradicional valenciano elaborado solo con ajo y aceite.","descripcion_en":"Traditional Valencian alioli made only with garlic and oil.","precio":4.50,"unidad":"ud","categoria":"conservas","stock":35,"stock_minimo":5,"destacado":True,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Gazpacho Artesanal 1L","nombre_en":"Artisan Gazpacho 1L","descripcion_es":"Gazpacho con tomate, pepino, pimiento y AOVE de la cooperativa.","descripcion_en":"Gazpacho with tomato, cucumber, pepper and cooperative EVOO.","precio":4.00,"unidad":"ud","categoria":"conservas","stock":40,"stock_minimo":5,"destacado":True,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Pimientos del Piquillo en Aceite 290g","nombre_en":"Piquillo Peppers in Oil 290g","descripcion_es":"Pimientos asados y pelados a mano, conservados en AOVE.","descripcion_en":"Hand-roasted and peeled peppers, preserved in EVOO.","precio":4.00,"unidad":"ud","categoria":"conservas","stock":50,"stock_minimo":8,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Vinagre de Vino Tinto Monastrell 500ml","nombre_en":"Monastrell Red Wine Vinegar 500ml","descripcion_es":"Vinagre artesanal de vino monastrell envejecido en barrica.","descripcion_en":"Artisan monastrell wine vinegar aged in barrel.","precio":5.00,"unidad":"ud","categoria":"conservas","stock":30,"stock_minimo":5,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Mojo Verde Cilantro 200g","nombre_en":"Coriander Green Mojo 200g","descripcion_es":"Salsa verde de cilantro, ajo y AOVE.","descripcion_en":"Green coriander, garlic and EVOO sauce.","precio":4.00,"unidad":"ud","categoria":"conservas","stock":30,"stock_minimo":5,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Sofrito de Verduras 400g","nombre_en":"Vegetable Sofrito 400g","descripcion_es":"Base de cocina con tomate, cebolla, ajo y pimiento.","descripcion_en":"Cooking base with tomato, onion, garlic and pepper.","precio":3.80,"unidad":"ud","categoria":"conservas","stock":50,"stock_minimo":8,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Mermelada de Granada 350g","nombre_en":"Pomegranate Jam 350g","descripcion_es":"Mermelada de granada mollar, color rubí y sabor dulce.","descripcion_en":"Mollar pomegranate jam, ruby colour and sweet flavour.","precio":5.50,"unidad":"ud","categoria":"conservas","stock":25,"stock_minimo":3,"destacado":True,"origen":"Elche, Alicante","certificado":None},
  {"nombre_es":"Pack Conservas Gourmet 5 uds","nombre_en":"Gourmet Preserves Pack 5 units","descripcion_es":"Selección de 5 conservas artesanales de la cooperativa. Ideal regalo.","descripcion_en":"Selection of 5 artisan preserves. Ideal as a gift.","precio":18.00,"unidad":"ud","categoria":"conservas","stock":15,"stock_minimo":3,"destacado":True,"origen":"Agost, Alicante","certificado":None},

  # ── VERDURAS ──────────────────────────────────────────────────
  {"nombre_es":"Tomate Raf","nombre_en":"Raf Tomato","descripcion_es":"Tomate rugoso de sabor intenso y baja acidez, el más apreciado.","descripcion_en":"Wrinkled tomato with intense flavour and low acidity, the most prized.","precio":3.50,"unidad":"kg","categoria":"verduras","stock":80,"stock_minimo":10,"destacado":True,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Tomate Cherry","nombre_en":"Cherry Tomato","descripcion_es":"Tomate pequeño y dulce, perfecto para ensaladas.","descripcion_en":"Small sweet tomato, perfect for salads.","precio":2.80,"unidad":"kg","categoria":"verduras","stock":70,"stock_minimo":10,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Tomate Pera","nombre_en":"Plum Tomato","descripcion_es":"Tomate alargado con poca agua, ideal para salsas.","descripcion_en":"Elongated low-water tomato, ideal for sauces.","precio":2.20,"unidad":"kg","categoria":"verduras","stock":90,"stock_minimo":10,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Pimiento Rojo Italiano","nombre_en":"Italian Red Pepper","descripcion_es":"Pimiento largo y carnoso, dulce, ideal para asar.","descripcion_en":"Long fleshy sweet pepper, ideal for roasting.","precio":2.50,"unidad":"kg","categoria":"verduras","stock":60,"stock_minimo":8,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Pimiento Verde Lamuyo","nombre_en":"Lamuyo Green Pepper","descripcion_es":"Pimiento cuadrado de gran tamaño, perfecto para rellenos.","descripcion_en":"Large square pepper, perfect for stuffing.","precio":2.00,"unidad":"kg","categoria":"verduras","stock":70,"stock_minimo":8,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Pimiento Padrón","nombre_en":"Padrón Pepper","descripcion_es":"Pimientos pequeños para freír, algunos pican y otros no.","descripcion_en":"Small peppers for frying, some hot some not.","precio":3.00,"unidad":"kg","categoria":"verduras","stock":50,"stock_minimo":5,"destacado":True,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Berenjena Negra","nombre_en":"Black Aubergine","descripcion_es":"Berenjena clásica de piel brillante y pulpa cremosa.","descripcion_en":"Classic aubergine with shiny skin and creamy flesh.","precio":1.80,"unidad":"kg","categoria":"verduras","stock":80,"stock_minimo":10,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Berenjena Rayada","nombre_en":"Striped Aubergine","descripcion_es":"Variedad italiana con piel rayada morada y blanca.","descripcion_en":"Italian variety with purple and white striped skin.","precio":2.20,"unidad":"kg","categoria":"verduras","stock":50,"stock_minimo":5,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Calabacín Verde","nombre_en":"Green Courgette","descripcion_es":"Calabacín de piel verde oscura, versátil en cocina.","descripcion_en":"Dark green-skinned courgette, versatile in cooking.","precio":1.50,"unidad":"kg","categoria":"verduras","stock":100,"stock_minimo":15,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Calabacín Amarillo","nombre_en":"Yellow Courgette","descripcion_es":"Calabacín dorado de sabor más suave y piel fina.","descripcion_en":"Golden courgette with milder flavour and thin skin.","precio":1.80,"unidad":"kg","categoria":"verduras","stock":60,"stock_minimo":8,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Calabacín Redondo","nombre_en":"Round Courgette","descripcion_es":"Variedad esférica perfecta para rellenar.","descripcion_en":"Spherical variety perfect for stuffing.","precio":2.00,"unidad":"kg","categoria":"verduras","stock":40,"stock_minimo":5,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Lechuga Romana","nombre_en":"Romaine Lettuce","descripcion_es":"Lechuga crujiente de hojas alargadas, base del César.","descripcion_en":"Crisp elongated-leafed lettuce, base of Caesar salad.","precio":1.20,"unidad":"ud","categoria":"verduras","stock":100,"stock_minimo":15,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Lechuga Batavia","nombre_en":"Batavia Lettuce","descripcion_es":"Lechuga de hoja rizada y textura crujiente.","descripcion_en":"Curly-leafed lettuce with crunchy texture.","precio":1.00,"unidad":"ud","categoria":"verduras","stock":90,"stock_minimo":15,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Rúcula Silvestre","nombre_en":"Wild Rocket","descripcion_es":"Rúcula de sabor intenso y picante, ideal para ensaladas gourmet.","descripcion_en":"Intense and peppery rocket, ideal for gourmet salads.","precio":2.50,"unidad":"bolsa 150g","categoria":"verduras","stock":60,"stock_minimo":8,"destacado":True,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Cebolla Valenciana","nombre_en":"Valencian Onion","descripcion_es":"Cebolla blanca dulce y jugosa, muy apreciada.","descripcion_en":"Sweet juicy white onion, highly prized.","precio":1.20,"unidad":"kg","categoria":"verduras","stock":120,"stock_minimo":15,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Cebolla Morada","nombre_en":"Red Onion","descripcion_es":"Cebolla de piel rojiza y sabor suave, ideal para ensaladas.","descripcion_en":"Red-skinned onion with milder flavour, ideal for salads.","precio":1.40,"unidad":"kg","categoria":"verduras","stock":80,"stock_minimo":10,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Ajo Blanco","nombre_en":"White Garlic","descripcion_es":"Ajo de cabeza blanca y sabor intenso, secado tradicional.","descripcion_en":"White-headed garlic with intense flavour, traditionally dried.","precio":4.00,"unidad":"kg","categoria":"verduras","stock":80,"stock_minimo":10,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Ajo Morado","nombre_en":"Purple Garlic","descripcion_es":"Ajo de Las Pedroñeras, el más valorado de España.","descripcion_en":"Las Pedroñeras purple garlic, the most prized in Spain.","precio":6.00,"unidad":"kg","categoria":"verduras","stock":50,"stock_minimo":8,"destacado":True,"origen":"España","certificado":"IGP Ajo Morado de Las Pedroñeras"},
  {"nombre_es":"Ajo Negro","nombre_en":"Black Garlic","descripcion_es":"Ajo fermentado de sabor dulce y umami, ingrediente gourmet.","descripcion_en":"Fermented garlic with sweet umami flavour, gourmet ingredient.","precio":12.00,"unidad":"kg","categoria":"verduras","stock":20,"stock_minimo":3,"destacado":True,"origen":"España","certificado":None},
  {"nombre_es":"Alcachofa Blanca de Tudela","nombre_en":"Tudela White Artichoke","descripcion_es":"Alcachofa tierna y sin espinas con denominación de origen.","descripcion_en":"Tender spine-free artichoke with designation of origin.","precio":3.50,"unidad":"kg","categoria":"verduras","stock":50,"stock_minimo":8,"destacado":True,"origen":"Navarra","certificado":"DO Alcachofa de Tudela"},
  {"nombre_es":"Alcachofa de Benicarló","nombre_en":"Benicarló Artichoke","descripcion_es":"Alcachofa IGP valenciana de sabor suave y corazón tierno.","descripcion_en":"Valencian IGP artichoke with mild flavour and tender heart.","precio":3.80,"unidad":"kg","categoria":"verduras","stock":40,"stock_minimo":5,"destacado":False,"origen":"Castellón","certificado":"IGP Alcachofa de Benicarló"},
  {"nombre_es":"Espárrago Verde","nombre_en":"Green Asparagus","descripcion_es":"Espárrago de temporada, tierno y con sabor intenso.","descripcion_en":"Seasonal asparagus, tender with intense field flavour.","precio":4.00,"unidad":"manojo","categoria":"verduras","stock":40,"stock_minimo":5,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Espárrago Blanco","nombre_en":"White Asparagus","descripcion_es":"Espárrago cultivado bajo tierra, suave y ligeramente amargo.","descripcion_en":"Underground-grown asparagus, mild and slightly bitter.","precio":6.00,"unidad":"manojo","categoria":"verduras","stock":25,"stock_minimo":3,"destacado":True,"origen":"España","certificado":None},
  {"nombre_es":"Brócoli Verde","nombre_en":"Green Broccoli","descripcion_es":"Brócoli de florets compactos, rico en vitamina C.","descripcion_en":"Broccoli with compact florets, rich in vitamin C.","precio":1.80,"unidad":"ud","categoria":"verduras","stock":80,"stock_minimo":10,"destacado":False,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Brócoli Romanesco","nombre_en":"Romanesco Broccoli","descripcion_es":"Variedad fractal de sabor suave, entre brócoli y coliflor.","descripcion_en":"Fractal variety with mild flavour, between broccoli and cauliflower.","precio":2.50,"unidad":"ud","categoria":"verduras","stock":40,"stock_minimo":5,"destacado":True,"origen":"Agost, Alicante","certificado":None},
  {"nombre_es":"Coliflor Blanca","nombre_en":"White Cauliflower","descripcion_es":"Coliflor compacta y blanca, ideal para gratinar.","descripcion_en":"Compact white cauliflower, ideal for gratinating.","precio":1.50,"unidad":"ud","categoria":"verduras","stock":70,"stock_minimo":10,"destacado":False,"origen":"Agost, Alicante","certificado":None},

  # ── ABONOS ────────────────────────────────────────────────────
  {"nombre_es":"Abono NPK 15-15-15 25kg","nombre_en":"NPK Fertilizer 15-15-15 25kg","descripcion_es":"Abono granulado equilibrado para todo tipo de cultivos.","descripcion_en":"Balanced granular fertilizer for all crop types.","precio":22.00,"unidad":"saco","categoria":"abonos","stock":50,"stock_minimo":5,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Abono Nitrogenado Urea 46% 25kg","nombre_en":"Nitrogen Urea 46% 25kg","descripcion_es":"Abono nitrogenado de alta concentración para fases vegetativas.","descripcion_en":"High-concentration nitrogen fertilizer for vegetative phases.","precio":18.00,"unidad":"saco","categoria":"abonos","stock":40,"stock_minimo":5,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Abono Potásico Sulfato de Potasio 25kg","nombre_en":"Potassium Sulphate 25kg","descripcion_es":"Mejora la calidad del fruto y la resistencia a enfermedades.","descripcion_en":"Improves fruit quality and disease resistance.","precio":25.00,"unidad":"saco","categoria":"abonos","stock":35,"stock_minimo":5,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Compost Ecológico Certificado 25kg","nombre_en":"Certified Organic Compost 25kg","descripcion_es":"Compost certificado ecológico que mejora la estructura del suelo.","descripcion_en":"Certified organic compost, improves soil structure.","precio":15.00,"unidad":"saco","categoria":"abonos","stock":60,"stock_minimo":8,"destacado":True,"origen":"España","certificado":"Ecológico"},
  {"nombre_es":"Humus de Lombriz 5L","nombre_en":"Worm Humus 5L","descripcion_es":"Vermicompost líquido, estimulante del crecimiento y enraizamiento.","descripcion_en":"Liquid vermicompost, growth and rooting stimulant.","precio":8.00,"unidad":"ud","categoria":"abonos","stock":40,"stock_minimo":5,"destacado":True,"origen":"España","certificado":"Ecológico"},
  {"nombre_es":"Guano de Murciélago 5kg","nombre_en":"Bat Guano 5kg","descripcion_es":"Abono orgánico de alta calidad, rico en nitrógeno y fósforo.","descripcion_en":"High-quality organic fertilizer, rich in nitrogen and phosphorus.","precio":12.00,"unidad":"ud","categoria":"abonos","stock":25,"stock_minimo":3,"destacado":False,"origen":"España","certificado":"Ecológico"},
  {"nombre_es":"Abono Foliar Calcio-Boro 1L","nombre_en":"Calcium-Boron Foliar 1L","descripcion_es":"Corrector foliar de carencias de calcio y boro.","descripcion_en":"Foliar corrector for calcium and boron deficiencies.","precio":14.00,"unidad":"ud","categoria":"abonos","stock":30,"stock_minimo":5,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Abono Fertirriego NPK 5L","nombre_en":"Fertigation NPK 5L","descripcion_es":"Solución nutritiva completa para riego por goteo.","descripcion_en":"Complete nutrient solution for drip irrigation.","precio":18.00,"unidad":"ud","categoria":"abonos","stock":25,"stock_minimo":3,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Bioestimulante Algas Marinas 1L","nombre_en":"Marine Algae Biostimulant 1L","descripcion_es":"Bioestimulante natural de algas, mejora el cuajado y la calidad del fruto.","descripcion_en":"Natural seaweed biostimulant, improves fruit set and quality.","precio":20.00,"unidad":"ud","categoria":"abonos","stock":20,"stock_minimo":3,"destacado":True,"origen":"España","certificado":"Ecológico"},
  {"nombre_es":"Roca Fosfórica Natural 25kg","nombre_en":"Natural Rock Phosphate 25kg","descripcion_es":"Fósforo de liberación lenta para agricultura ecológica.","descripcion_en":"Slow-release phosphorus for organic farming.","precio":16.00,"unidad":"saco","categoria":"abonos","stock":20,"stock_minimo":3,"destacado":False,"origen":"España","certificado":"Ecológico"},

  # ── FITOSANITARIOS ────────────────────────────────────────────
  {"nombre_es":"Fungicida Cobre Líquido 1L","nombre_en":"Liquid Copper Fungicide 1L","descripcion_es":"Fungicida cúprico para mildiu, alternaria y otras enfermedades fúngicas.","descripcion_en":"Copper fungicide for mildew, alternaria and other fungal diseases.","precio":12.00,"unidad":"ud","categoria":"fitosanitarios","stock":40,"stock_minimo":5,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Insecticida Azadiractina Neem 1L","nombre_en":"Neem Azadirachtin Insecticide 1L","descripcion_es":"Insecticida natural de nim, compatible con producción ecológica.","descripcion_en":"Natural neem insecticide, compatible with organic production.","precio":18.00,"unidad":"ud","categoria":"fitosanitarios","stock":30,"stock_minimo":5,"destacado":True,"origen":"España","certificado":"Ecológico"},
  {"nombre_es":"Herbicida Sistémico Total 1L","nombre_en":"Total Systemic Herbicide 1L","descripcion_es":"Herbicida sistémico de amplio espectro para malas hierbas.","descripcion_en":"Broad-spectrum systemic herbicide for weeds.","precio":10.00,"unidad":"ud","categoria":"fitosanitarios","stock":50,"stock_minimo":8,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Acaricida Abamectina 250ml","nombre_en":"Abamectin Acaricide 250ml","descripcion_es":"Acaricida para araña roja y otros ácaros en frutales.","descripcion_en":"Acaricide for red spider mite and other mites on fruit trees.","precio":22.00,"unidad":"ud","categoria":"fitosanitarios","stock":20,"stock_minimo":3,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Kaolín Barrera Física 5kg","nombre_en":"Kaolin Physical Barrier 5kg","descripcion_es":"Barrera de caolín contra mosca de la fruta y trips. Ecológico.","descripcion_en":"Kaolin barrier against fruit fly and thrips. Organic.","precio":15.00,"unidad":"ud","categoria":"fitosanitarios","stock":25,"stock_minimo":3,"destacado":True,"origen":"España","certificado":"Ecológico"},
  {"nombre_es":"Bacillus thuringiensis 500g","nombre_en":"Bacillus thuringiensis 500g","descripcion_es":"Insecticida biológico contra orugas y lepidópteros.","descripcion_en":"Biological insecticide against caterpillars and lepidoptera.","precio":16.00,"unidad":"ud","categoria":"fitosanitarios","stock":20,"stock_minimo":3,"destacado":False,"origen":"España","certificado":"Ecológico"},
  {"nombre_es":"Trampas Cromotrópicas Amarillas 10 uds","nombre_en":"Yellow Chromotropic Traps 10 units","descripcion_es":"Trampas adhesivas para monitoreo de mosca blanca y minadores.","descripcion_en":"Sticky traps for whitefly and leafminer monitoring.","precio":8.00,"unidad":"ud","categoria":"fitosanitarios","stock":40,"stock_minimo":5,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Caldo Bordelés Preparado 5L","nombre_en":"Bordeaux Mixture 5L","descripcion_es":"Mezcla de sulfato de cobre y cal, fungicida clásico para viña y olivo.","descripcion_en":"Copper sulphate and lime mixture, classic fungicide.","precio":14.00,"unidad":"ud","categoria":"fitosanitarios","stock":30,"stock_minimo":5,"destacado":False,"origen":"España","certificado":"Ecológico"},
  {"nombre_es":"Aceite de Parafina Insecticida 1L","nombre_en":"Paraffin Oil Insecticide 1L","descripcion_es":"Insecticida de contacto asfixiante para cochinillas y pulgones.","descripcion_en":"Contact asphyxiant insecticide for scale insects and aphids.","precio":9.00,"unidad":"ud","categoria":"fitosanitarios","stock":35,"stock_minimo":5,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Feromona Mosca Olivo Prays","nombre_en":"Olive Moth Pheromone Prays","descripcion_es":"Feromona sexual para captura y monitoreo de polilla del olivo.","descripcion_en":"Sex pheromone for capture and monitoring of olive moth.","precio":12.00,"unidad":"ud","categoria":"fitosanitarios","stock":15,"stock_minimo":3,"destacado":False,"origen":"España","certificado":None},

  # ── SEMILLAS ──────────────────────────────────────────────────
  {"nombre_es":"Semillas Tomate Raf 0.5g","nombre_en":"Raf Tomato Seeds 0.5g","descripcion_es":"Semillas de tomate raf de alta germinación.","descripcion_en":"High-germination raf tomato seeds.","precio":3.50,"unidad":"sobre","categoria":"semillas","stock":50,"stock_minimo":5,"destacado":True,"origen":"España","certificado":None},
  {"nombre_es":"Semillas Tomate Cherry Rojo 0.5g","nombre_en":"Red Cherry Tomato Seeds 0.5g","descripcion_es":"Tomate cherry rojo, productivo y fácil de cultivar.","descripcion_en":"Red cherry tomato, productive and easy to grow.","precio":2.80,"unidad":"sobre","categoria":"semillas","stock":60,"stock_minimo":5,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Semillas Tomate Negro Crimea 0.5g","nombre_en":"Black Crimea Tomato Seeds 0.5g","descripcion_es":"Tomate herencia de pulpa oscura y sabor complejo.","descripcion_en":"Heirloom tomato with dark flesh and complex flavour.","precio":4.00,"unidad":"sobre","categoria":"semillas","stock":30,"stock_minimo":3,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Semillas Pimiento California 1g","nombre_en":"California Pepper Seeds 1g","descripcion_es":"Pimiento cuadrado dulce, fácil cultivo en huerto.","descripcion_en":"Sweet square pepper, easy to grow in garden.","precio":2.50,"unidad":"sobre","categoria":"semillas","stock":50,"stock_minimo":5,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Semillas Pimiento Picante Cayena 1g","nombre_en":"Cayenne Chilli Seeds 1g","descripcion_es":"Pimiento picante para secar y moler como especia.","descripcion_en":"Hot pepper for drying and grinding as a spice.","precio":2.80,"unidad":"sobre","categoria":"semillas","stock":40,"stock_minimo":5,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Semillas Pimiento Morro Rojo 1g","nombre_en":"Red Morro Pepper Seeds 1g","descripcion_es":"Pimiento de morro rojo, dulce y carnoso, ideal para asar.","descripcion_en":"Red morro pepper, sweet and fleshy, ideal for roasting.","precio":3.00,"unidad":"sobre","categoria":"semillas","stock":35,"stock_minimo":3,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Semillas Calabacín Verde 2g","nombre_en":"Green Courgette Seeds 2g","descripcion_es":"Calabacín productivo y resistente, ideal para principiantes.","descripcion_en":"Productive and resilient courgette, ideal for beginners.","precio":2.00,"unidad":"sobre","categoria":"semillas","stock":60,"stock_minimo":5,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Semillas Calabacín Amarillo 2g","nombre_en":"Yellow Courgette Seeds 2g","descripcion_es":"Calabacín dorado de sabor delicado y decorativo.","descripcion_en":"Golden courgette with delicate flavour, decorative.","precio":2.50,"unidad":"sobre","categoria":"semillas","stock":45,"stock_minimo":5,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Semillas Calabaza Violín 3g","nombre_en":"Butternut Squash Seeds 3g","descripcion_es":"Calabaza de invierno de cuello alargado, muy dulce.","descripcion_en":"Winter squash with elongated neck, very sweet.","precio":2.80,"unidad":"sobre","categoria":"semillas","stock":40,"stock_minimo":5,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Semillas Lechuga Batavia 1g","nombre_en":"Batavia Lettuce Seeds 1g","descripcion_es":"Lechuga resistente al calor, ideal para verano.","descripcion_en":"Heat-resistant lettuce, ideal for summer.","precio":1.80,"unidad":"sobre","categoria":"semillas","stock":70,"stock_minimo":5,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Semillas Lechuga Romana 1g","nombre_en":"Romaine Lettuce Seeds 1g","descripcion_es":"Lechuga de hojas largas y crujientes.","descripcion_en":"Long crispy-leafed lettuce.","precio":1.80,"unidad":"sobre","categoria":"semillas","stock":70,"stock_minimo":5,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Semillas Mezcla Mesclun 2g","nombre_en":"Mesclun Mix Seeds 2g","descripcion_es":"Mezcla de hojas para ensalada: rúcula, escarola, canónigos.","descripcion_en":"Salad leaf mix: rocket, endive, lamb's lettuce.","precio":2.50,"unidad":"sobre","categoria":"semillas","stock":50,"stock_minimo":5,"destacado":True,"origen":"España","certificado":None},
  {"nombre_es":"Semillas Albahaca Genovesa 0.5g","nombre_en":"Genovese Basil Seeds 0.5g","descripcion_es":"Albahaca de hoja grande para pesto y cocina mediterránea.","descripcion_en":"Large-leafed basil for pesto and Mediterranean cooking.","precio":1.50,"unidad":"sobre","categoria":"semillas","stock":80,"stock_minimo":8,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Semillas Albahaca Morada 0.5g","nombre_en":"Purple Basil Seeds 0.5g","descripcion_es":"Albahaca decorativa y aromática, sabor anisado.","descripcion_en":"Decorative and aromatic basil, anise flavour.","precio":2.00,"unidad":"sobre","categoria":"semillas","stock":50,"stock_minimo":5,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Semillas Zanahoria Nantes 2g","nombre_en":"Nantes Carrot Seeds 2g","descripcion_es":"Zanahoria cilíndrica dulce y tierna.","descripcion_en":"Sweet tender cylindrical carrot.","precio":1.80,"unidad":"sobre","categoria":"semillas","stock":60,"stock_minimo":5,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Semillas Zanahoria Morada 2g","nombre_en":"Purple Carrot Seeds 2g","descripcion_es":"Zanahoria de color morado intenso, rica en antocianinas.","descripcion_en":"Deep purple carrot, rich in anthocyanins.","precio":2.50,"unidad":"sobre","categoria":"semillas","stock":35,"stock_minimo":3,"destacado":True,"origen":"España","certificado":None},
  {"nombre_es":"Semillas Remolacha Roja 3g","nombre_en":"Red Beetroot Seeds 3g","descripcion_es":"Remolacha clásica de pulpa roja intensa.","descripcion_en":"Classic beetroot with intense red flesh.","precio":2.00,"unidad":"sobre","categoria":"semillas","stock":50,"stock_minimo":5,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Semillas Remolacha Chioggia 3g","nombre_en":"Chioggia Beetroot Seeds 3g","descripcion_es":"Remolacha italiana con anillos concéntricos rosados y blancos.","descripcion_en":"Italian beetroot with pink and white concentric rings.","precio":2.80,"unidad":"sobre","categoria":"semillas","stock":25,"stock_minimo":3,"destacado":True,"origen":"España","certificado":None},
  {"nombre_es":"Semillas Espinaca Gigante Invierno 3g","nombre_en":"Giant Winter Spinach Seeds 3g","descripcion_es":"Espinaca de hoja grande resistente al frío.","descripcion_en":"Large-leaved cold-resistant spinach.","precio":1.80,"unidad":"sobre","categoria":"semillas","stock":60,"stock_minimo":5,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Semillas Acelga Rainbow 3g","nombre_en":"Rainbow Chard Seeds 3g","descripcion_es":"Acelga de pencas multicolor, decorativa y nutritiva.","descripcion_en":"Multicoloured stemmed chard, decorative and nutritious.","precio":2.50,"unidad":"sobre","categoria":"semillas","stock":40,"stock_minimo":5,"destacado":True,"origen":"España","certificado":None},
  {"nombre_es":"Semillas Guisante Lágrima 10g","nombre_en":"Teardrop Pea Seeds 10g","descripcion_es":"Guisante dulce de grano pequeño, el más apreciado en gastronomía.","descripcion_en":"Sweet small-grained pea, the most prized in gastronomy.","precio":3.50,"unidad":"sobre","categoria":"semillas","stock":30,"stock_minimo":3,"destacado":True,"origen":"España","certificado":None},
  {"nombre_es":"Semillas Judía Verde Perona 5g","nombre_en":"Perona French Bean Seeds 5g","descripcion_es":"Judía plana ancha, muy productiva y sin hebra.","descripcion_en":"Wide flat bean, very productive and stringless.","precio":2.00,"unidad":"sobre","categoria":"semillas","stock":55,"stock_minimo":5,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Semillas Cebollino 1g","nombre_en":"Chive Seeds 1g","descripcion_es":"Hierba aromática perenne, fácil de cultivar en maceta.","descripcion_en":"Perennial aromatic herb, easy to grow in a pot.","precio":1.50,"unidad":"sobre","categoria":"semillas","stock":70,"stock_minimo":8,"destacado":False,"origen":"España","certificado":None},

  # ── ARBOLITOS ─────────────────────────────────────────────────
  {"nombre_es":"Almendro Marcona 2 años","nombre_en":"Marcona Almond Tree 2 years","descripcion_es":"Planta de almendro marcona injertada en patrón GF677.","descripcion_en":"Marcona almond plant grafted on GF677 rootstock.","precio":12.00,"unidad":"ud","categoria":"arbolitos","stock":30,"stock_minimo":3,"destacado":True,"origen":"Vivero Alicante","certificado":"Vivero certificado"},
  {"nombre_es":"Almendro Largueta 2 años","nombre_en":"Largueta Almond Tree 2 years","descripcion_es":"Almendro autofértil de floración tardía, escapa a las heladas.","descripcion_en":"Self-fertile almond tree with late flowering, avoids frost.","precio":12.00,"unidad":"ud","categoria":"arbolitos","stock":25,"stock_minimo":3,"destacado":False,"origen":"Vivero Alicante","certificado":"Vivero certificado"},
  {"nombre_es":"Almendro Guara 2 años","nombre_en":"Guara Almond Tree 2 years","descripcion_es":"Variedad autofértil de alta producción y cosecha mecanizable.","descripcion_en":"Self-fertile high-yield variety with mechanisable harvest.","precio":11.00,"unidad":"ud","categoria":"arbolitos","stock":20,"stock_minimo":3,"destacado":False,"origen":"Vivero Alicante","certificado":"Vivero certificado"},
  {"nombre_es":"Olivo Arbequina 2 años","nombre_en":"Arbequina Olive Tree 2 years","descripcion_es":"Olivo compacto de alta producción, perfecto para olivar intensivo.","descripcion_en":"Compact high-yield olive tree, perfect for intensive olive growing.","precio":10.00,"unidad":"ud","categoria":"arbolitos","stock":40,"stock_minimo":5,"destacado":True,"origen":"Vivero Alicante","certificado":"Vivero certificado"},
  {"nombre_es":"Olivo Picual 2 años","nombre_en":"Picual Olive Tree 2 years","descripcion_es":"El olivo más cultivado en España, aceite de gran calidad.","descripcion_en":"The most cultivated olive in Spain, high-quality oil.","precio":10.00,"unidad":"ud","categoria":"arbolitos","stock":35,"stock_minimo":5,"destacado":False,"origen":"Vivero Alicante","certificado":"Vivero certificado"},
  {"nombre_es":"Olivo Centenario Ornamental","nombre_en":"Ornamental Centenary Olive","descripcion_es":"Olivo adulto con tronco retorcido para jardín y decoración.","descripcion_en":"Mature olive with twisted trunk for garden and decoration.","precio":150.00,"unidad":"ud","categoria":"arbolitos","stock":5,"stock_minimo":1,"destacado":True,"origen":"Alicante","certificado":None},
  {"nombre_es":"Naranjo Navel 2 años","nombre_en":"Navel Orange Tree 2 years","descripcion_es":"Naranjo de mesa sin semillas injertado en Citrus aurantium.","descripcion_en":"Seedless table orange grafted on Citrus aurantium.","precio":14.00,"unidad":"ud","categoria":"arbolitos","stock":25,"stock_minimo":3,"destacado":False,"origen":"Vivero Valencia","certificado":"Vivero certificado"},
  {"nombre_es":"Limonero Verna 2 años","nombre_en":"Verna Lemon Tree 2 years","descripcion_es":"Limonero vigoroso de dos cosechas anuales.","descripcion_en":"Vigorous lemon tree with two annual harvests.","precio":12.00,"unidad":"ud","categoria":"arbolitos","stock":30,"stock_minimo":3,"destacado":False,"origen":"Vivero Valencia","certificado":"Vivero certificado"},
  {"nombre_es":"Mandarino Clementina 2 años","nombre_en":"Clementine Mandarin Tree 2 years","descripcion_es":"Mandarino precoz de fruto sin semillas y fácil pelado.","descripcion_en":"Early mandarin with seedless easy-peel fruit.","precio":13.00,"unidad":"ud","categoria":"arbolitos","stock":20,"stock_minimo":3,"destacado":False,"origen":"Vivero Valencia","certificado":"Vivero certificado"},
  {"nombre_es":"Vid Monastrell 1 año","nombre_en":"Monastrell Vine 1 year","descripcion_es":"Sarmiento enraizado de monastrell, variedad autóctona de Alicante.","descripcion_en":"Rooted monastrell cutting, native Alicante variety.","precio":4.50,"unidad":"ud","categoria":"arbolitos","stock":50,"stock_minimo":5,"destacado":True,"origen":"Vivero Alicante","certificado":"Vivero certificado"},
  {"nombre_es":"Vid Moscatel 1 año","nombre_en":"Muscat Vine 1 year","descripcion_es":"Moscatel de Alexandria, uva de mesa y vinificación aromática.","descripcion_en":"Muscat of Alexandria, table and aromatic wine grape.","precio":5.00,"unidad":"ud","categoria":"arbolitos","stock":40,"stock_minimo":5,"destacado":False,"origen":"Vivero Alicante","certificado":"Vivero certificado"},
  {"nombre_es":"Granado Mollar 2 años","nombre_en":"Mollar Pomegranate Tree 2 years","descripcion_es":"Granado de fruto dulce sin semilla dura, DO Elche.","descripcion_en":"Pomegranate tree with sweet seedless fruit.","precio":15.00,"unidad":"ud","categoria":"arbolitos","stock":15,"stock_minimo":3,"destacado":True,"origen":"Vivero Alicante","certificado":"Vivero certificado"},
  {"nombre_es":"Higuera Cuello de Dama 2 años","nombre_en":"Cuello de Dama Fig Tree 2 years","descripcion_es":"Higuera de brevas grandes y dulces, variedad histórica española.","descripcion_en":"Fig tree with large sweet early figs, historic Spanish variety.","precio":13.00,"unidad":"ud","categoria":"arbolitos","stock":20,"stock_minimo":3,"destacado":False,"origen":"Vivero Alicante","certificado":"Vivero certificado"},
  {"nombre_es":"Algarrobo 2 años","nombre_en":"Carob Tree 2 years","descripcion_es":"Árbol mediterráneo de secano con múltiples usos agroalimentarios.","descripcion_en":"Mediterranean dry-land tree with multiple agri-food uses.","precio":10.00,"unidad":"ud","categoria":"arbolitos","stock":20,"stock_minimo":3,"destacado":False,"origen":"Vivero Alicante","certificado":"Vivero certificado"},
  {"nombre_es":"Melocotonero Amarillo 2 años","nombre_en":"Yellow Peach Tree 2 years","descripcion_es":"Melocotonero de fruto grande y jugoso, injertado en GF305.","descripcion_en":"Large juicy-fruited peach tree, grafted on GF305.","precio":12.00,"unidad":"ud","categoria":"arbolitos","stock":20,"stock_minimo":3,"destacado":False,"origen":"Vivero Alicante","certificado":"Vivero certificado"},
  {"nombre_es":"Aguacate Hass 2 años","nombre_en":"Hass Avocado Tree 2 years","descripcion_es":"Aguacate injertado en Drymifolia, la variedad más comercial.","descripcion_en":"Avocado grafted on Drymifolia, world's most commercial variety.","precio":18.00,"unidad":"ud","categoria":"arbolitos","stock":15,"stock_minimo":3,"destacado":True,"origen":"Vivero Málaga","certificado":"Vivero certificado"},
  {"nombre_es":"Nogal Común 2 años","nombre_en":"Common Walnut Tree 2 years","descripcion_es":"Nogal de crecimiento vigoroso para producción de nuez.","descripcion_en":"Vigorous-growing walnut for nut production.","precio":14.00,"unidad":"ud","categoria":"arbolitos","stock":15,"stock_minimo":3,"destacado":False,"origen":"Vivero Alicante","certificado":"Vivero certificado"},
  {"nombre_es":"Pino Piñonero 2 años","nombre_en":"Stone Pine 2 years","descripcion_es":"Pino mediterráneo productor de piñones, ornamental y productivo.","descripcion_en":"Mediterranean pine producing pine nuts, ornamental and productive.","precio":8.00,"unidad":"ud","categoria":"arbolitos","stock":25,"stock_minimo":3,"destacado":False,"origen":"Vivero Alicante","certificado":"Vivero certificado"},

  # ── HERRAMIENTAS ──────────────────────────────────────────────
  {"nombre_es":"Azada de Aporcado 180mm","nombre_en":"Ridging Hoe 180mm","descripcion_es":"Azada de acero forjado con mango de fresno, resistente y equilibrada.","descripcion_en":"Forged steel hoe with ash handle, sturdy and balanced.","precio":18.00,"unidad":"ud","categoria":"herramientas","stock":20,"stock_minimo":3,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Podadera Bypass Profesional","nombre_en":"Professional Bypass Pruner","descripcion_es":"Tijera de podar de doble filo para ramas hasta 25mm.","descripcion_en":"Double-blade pruner for branches up to 25mm.","precio":28.00,"unidad":"ud","categoria":"herramientas","stock":25,"stock_minimo":3,"destacado":True,"origen":"España","certificado":None},
  {"nombre_es":"Mochila Sulfatadora Manual 16L","nombre_en":"16L Manual Sprayer Backpack","descripcion_es":"Mochila pulverizadora con lanza telescópica y boquilla ajustable.","descripcion_en":"Sprayer backpack with telescopic lance and adjustable nozzle.","precio":45.00,"unidad":"ud","categoria":"herramientas","stock":15,"stock_minimo":2,"destacado":True,"origen":"España","certificado":None},
  {"nombre_es":"Pala de Plantación Estrecha","nombre_en":"Narrow Planting Spade","descripcion_es":"Pala laya estrecha para trasplante y plantación en línea.","descripcion_en":"Narrow spade for transplanting and row planting.","precio":22.00,"unidad":"ud","categoria":"herramientas","stock":15,"stock_minimo":2,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Rastrillo de Jardín 14 dientes","nombre_en":"14-Tine Garden Rake","descripcion_es":"Rastrillo de acero galvanizado para nivelar y mullir el suelo.","descripcion_en":"Galvanised steel rake for levelling and loosening soil.","precio":16.00,"unidad":"ud","categoria":"herramientas","stock":20,"stock_minimo":3,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Tijeras de Vendimiar Inox","nombre_en":"Stainless Steel Grape Scissors","descripcion_es":"Tijeras curvas de acero inoxidable para vendimia y poda verde.","descripcion_en":"Curved stainless steel scissors for harvesting and green pruning.","precio":14.00,"unidad":"ud","categoria":"herramientas","stock":30,"stock_minimo":5,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Cultivador de Mano 3 dientes","nombre_en":"3-Tine Hand Cultivator","descripcion_es":"Cultivador para desherbado y aireación entre plantas.","descripcion_en":"Cultivator for weeding and aeration between plants.","precio":9.00,"unidad":"ud","categoria":"herramientas","stock":25,"stock_minimo":3,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Serrucho de Poda Curvo 35cm","nombre_en":"35cm Curved Pruning Saw","descripcion_es":"Serrucho de corte en tracción para ramas hasta 15cm.","descripcion_en":"Pull-cut saw for branches up to 15cm diameter.","precio":20.00,"unidad":"ud","categoria":"herramientas","stock":15,"stock_minimo":2,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Afilador Universal de Herramientas","nombre_en":"Universal Tool Sharpener","descripcion_es":"Afilador de carburo para tijeras, cuchillos y herramientas de corte.","descripcion_en":"Carbide sharpener for scissors, knives and cutting tools.","precio":12.00,"unidad":"ud","categoria":"herramientas","stock":20,"stock_minimo":3,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Carretilla de Jardín 65L","nombre_en":"65L Garden Wheelbarrow","descripcion_es":"Carretilla de polipropileno con rueda neumática, ligera y resistente.","descripcion_en":"Polypropylene wheelbarrow with pneumatic wheel, light and sturdy.","precio":55.00,"unidad":"ud","categoria":"herramientas","stock":8,"stock_minimo":1,"destacado":False,"origen":"España","certificado":None},

  # ── EQUIPACIÓN ────────────────────────────────────────────────
  {"nombre_es":"Guantes Anticorte Nivel 3 Talla M","nombre_en":"Level 3 Cut-Resistant Gloves M","descripcion_es":"Guantes de trabajo con palma de nitrilo y protección anticorte.","descripcion_en":"Work gloves with nitrile palm and cut protection.","precio":8.50,"unidad":"par","categoria":"equipacion","stock":40,"stock_minimo":5,"destacado":False,"origen":"España","certificado":"CE"},
  {"nombre_es":"Guantes Anticorte Nivel 3 Talla L","nombre_en":"Level 3 Cut-Resistant Gloves L","descripcion_es":"Guantes de trabajo con palma de nitrilo y protección anticorte.","descripcion_en":"Work gloves with nitrile palm and cut protection.","precio":8.50,"unidad":"par","categoria":"equipacion","stock":40,"stock_minimo":5,"destacado":False,"origen":"España","certificado":"CE"},
  {"nombre_es":"Guantes de Vendimia Talla M","nombre_en":"Harvest Gloves Size M","descripcion_es":"Guantes finos de látex para vendimia y recolección de fruta.","descripcion_en":"Fine latex gloves for grape and fruit harvesting.","precio":5.00,"unidad":"par","categoria":"equipacion","stock":50,"stock_minimo":8,"destacado":False,"origen":"España","certificado":"CE"},
  {"nombre_es":"Mono de Trabajo Verde Talla M","nombre_en":"Green Work Overalls Size M","descripcion_es":"Mono de algodón resistente con múltiples bolsillos.","descripcion_en":"Sturdy cotton overalls with multiple pockets.","precio":32.00,"unidad":"ud","categoria":"equipacion","stock":15,"stock_minimo":2,"destacado":False,"origen":"España","certificado":"CE"},
  {"nombre_es":"Mono de Trabajo Verde Talla L","nombre_en":"Green Work Overalls Size L","descripcion_es":"Mono de algodón resistente con múltiples bolsillos.","descripcion_en":"Sturdy cotton overalls with multiple pockets.","precio":32.00,"unidad":"ud","categoria":"equipacion","stock":15,"stock_minimo":2,"destacado":False,"origen":"España","certificado":"CE"},
  {"nombre_es":"Mono de Trabajo Verde Talla XL","nombre_en":"Green Work Overalls Size XL","descripcion_es":"Mono de algodón resistente con múltiples bolsillos.","descripcion_en":"Sturdy cotton overalls with multiple pockets.","precio":34.00,"unidad":"ud","categoria":"equipacion","stock":12,"stock_minimo":2,"destacado":False,"origen":"España","certificado":"CE"},
  {"nombre_es":"Mascarilla FFP2 Sin Válvula 5 uds","nombre_en":"FFP2 Mask Without Valve 5 units","descripcion_es":"Mascarilla de protección respiratoria para fitosanitarios y polvo.","descripcion_en":"Respiratory protection mask for pesticides and dust.","precio":6.50,"unidad":"caja","categoria":"equipacion","stock":60,"stock_minimo":10,"destacado":False,"origen":"España","certificado":"CE FFP2"},
  {"nombre_es":"Gafas de Protección Panorámicas","nombre_en":"Panoramic Safety Goggles","descripcion_es":"Gafas de protección con ventilación indirecta, antiempañante.","descripcion_en":"Safety goggles with indirect ventilation, anti-fog.","precio":7.00,"unidad":"ud","categoria":"equipacion","stock":30,"stock_minimo":5,"destacado":False,"origen":"España","certificado":"CE EN166"},
  {"nombre_es":"Sombrero de Paja Ala Ancha","nombre_en":"Wide-Brim Straw Hat","descripcion_es":"Sombrero de paja natural para protección solar en campo.","descripcion_en":"Natural straw hat for sun protection in the field.","precio":12.00,"unidad":"ud","categoria":"equipacion","stock":20,"stock_minimo":3,"destacado":False,"origen":"España","certificado":None},
  {"nombre_es":"Botas de Agua Verde Talla 42","nombre_en":"Green Rubber Boots Size 42","descripcion_es":"Botas de PVC resistentes al agua y productos químicos.","descripcion_en":"PVC boots resistant to water and chemicals.","precio":22.00,"unidad":"par","categoria":"equipacion","stock":10,"stock_minimo":2,"destacado":False,"origen":"España","certificado":"CE"},
  {"nombre_es":"Mochila Sulfatadora Eléctrica 16L","nombre_en":"16L Electric Sprayer Backpack","descripcion_es":"Mochila pulverizadora con motor eléctrico 12V y batería recargable.","descripcion_en":"Electric sprayer backpack with 12V motor and rechargeable battery.","precio":85.00,"unidad":"ud","categoria":"equipacion","stock":8,"stock_minimo":1,"destacado":True,"origen":"España","certificado":"CE"},
  {"nombre_es":"Arnés de Seguridad Poda en Altura","nombre_en":"Safety Harness for High Pruning","descripcion_es":"Arnés completo homologado para trabajo en altura con árboles.","descripcion_en":"Full approved harness for working at height in trees.","precio":65.00,"unidad":"ud","categoria":"equipacion","stock":5,"stock_minimo":1,"destacado":False,"origen":"España","certificado":"CE EN361"},
]

creados = 0
existentes = 0
for p in productos:
    existe = db.query(Producto).filter(Producto.nombre_es == p["nombre_es"]).first()
    if existe:
        existentes += 1
        continue
    nuevo = Producto(**p)
    db.add(nuevo)
    creados += 1

db.commit()
db.close()
print(f"✅ {creados} productos creados. {existentes} ya existían.")
print(f"📦 Total procesados: {creados + existentes}")
