"""crear tabla aportaciones

Revision ID: 1e3a6df4e684
Revises: 9092ba427d8e
Create Date: 2026-03-27 08:16:57.190711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e3a6df4e684'
down_revision: Union[str, Sequence[str], None] = '9092ba427d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aportaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('socio_id', sa.Integer(), nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('producto', sa.String(length=100), nullable=False),
    sa.Column('kg', sa.Float(), nullable=False),
    sa.Column('precio_kg', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('notas', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['socio_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['trabajador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aportaciones')
    # ### end Alembic commands ###
