"""crear tablas mensajes planes anotaciones sensores

Revision ID: 7dd5dab2b423
Revises: 1e3a6df4e684
Create Date: 2026-03-27 10:29:00.787492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dd5dab2b423'
down_revision: Union[str, Sequence[str], None] = '1e3a6df4e684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecturas_sensor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('temp_aire', sa.Float(), nullable=True),
    sa.Column('hum_aire', sa.Float(), nullable=True),
    sa.Column('hum_suelo', sa.Float(), nullable=True),
    sa.Column('temp_suelo', sa.Float(), nullable=True),
    sa.Column('luz_lux', sa.Float(), nullable=True),
    sa.Column('lluvia_raw', sa.Integer(), nullable=True),
    sa.Column('nivel_agua_cm', sa.Float(), nullable=True),
    sa.Column('ph_suelo', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_device_ts', 'lecturas_sensor', ['device_id', 'timestamp'], unique=True)
    op.create_index(op.f('ix_lecturas_sensor_device_id'), 'lecturas_sensor', ['device_id'], unique=False)
    op.create_table('mensajes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('de_id', sa.Integer(), nullable=False),
    sa.Column('para_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=1000), nullable=False),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['de_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['para_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planes_accion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('socio_id', sa.Integer(), nullable=False),
    sa.Column('ingeniero_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ingeniero_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['socio_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anotaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parcela_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=1000), nullable=False),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('synced', sa.Boolean(), nullable=True),
    sa.Column('device_ts', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anotaciones')
    op.drop_table('planes_accion')
    op.drop_table('mensajes')
    op.drop_index(op.f('ix_lecturas_sensor_device_id'), table_name='lecturas_sensor')
    op.drop_index('ix_device_ts', table_name='lecturas_sensor')
    op.drop_table('lecturas_sensor')
    # ### end Alembic commands ###
