"""crear tablas aperos y alquileres

Revision ID: 9092ba427d8e
Revises: f0ef47c07c56
Create Date: 2026-03-25 08:20:55.376938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9092ba427d8e'
down_revision: Union[str, Sequence[str], None] = 'f0ef47c07c56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aperos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('precio_dia', sa.Float(), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.Column('imagen_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alquileres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('apero_id', sa.Integer(), nullable=False),
    sa.Column('socio_id', sa.Integer(), nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=False),
    sa.Column('precio_total', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('observaciones', sa.String(length=300), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['apero_id'], ['aperos.id'], ),
    sa.ForeignKeyConstraint(['socio_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['trabajador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alquileres')
    op.drop_table('aperos')
    # ### end Alembic commands ###
