"""añadir lat lon a parcelas

Revision ID: afdca0d5d6e0
Revises: 7dd5dab2b423
Create Date: 2026-04-24 10:52:19.707873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afdca0d5d6e0'
down_revision: Union[str, Sequence[str], None] = '7dd5dab2b423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
