"""crear tabla parcelas

Revision ID: e684dd4af9f3
Revises: f1597a2a98dc
Create Date: 2026-03-18 11:15:21.695382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e684dd4af9f3'
down_revision: Union[str, Sequence[str], None] = 'f1597a2a98dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcelas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('superficie_ha', sa.Float(), nullable=False),
    sa.Column('cultivo', sa.String(length=100), nullable=False),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('geojson', sa.Text(), nullable=True),
    sa.Column('agricultor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agricultor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parcelas')
    # ### end Alembic commands ###
