"""crear tablas productos y ventas

Revision ID: ff8cb4957fc4
Revises: e684dd4af9f3
Create Date: 2026-03-18 11:52:31.939461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff8cb4957fc4'
down_revision: Union[str, Sequence[str], None] = 'e684dd4af9f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_es', sa.String(length=200), nullable=False),
    sa.Column('nombre_en', sa.String(length=200), nullable=False),
    sa.Column('descripcion_es', sa.Text(), nullable=False),
    sa.Column('descripcion_en', sa.Text(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('stock_minimo', sa.Integer(), nullable=True),
    sa.Column('imagen_url', sa.String(length=500), nullable=True),
    sa.Column('destacado', sa.Boolean(), nullable=True),
    sa.Column('origen', sa.String(length=100), nullable=True),
    sa.Column('certificado', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_categoria'), 'productos', ['categoria'], unique=False)
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('socio_id', sa.Integer(), nullable=True),
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('ticket_pdf_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['socio_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['trabajador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lineas_venta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_ud', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lineas_venta')
    op.drop_table('ventas')
    op.drop_index(op.f('ix_productos_categoria'), table_name='productos')
    op.drop_table('productos')
    # ### end Alembic commands ###
